// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from '@lezer/lr';

export const parser = LRParser.deserialize({
  version: 14,
  states: "hQQOPOOQQOPOOOOOO'#C_'#C_OOOO-E6]-E6]",
  stateData: 'V~OQQO~O',
  goto: 'ZSPPPTQPORRP',
  nodeNames: '⚠ Program DynamicTerm',
  maxTerm: 4,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData:
    "#X~RP#o#pU~XP#o#p[~_WOY[Zr[s#O[#P#q[#q#rw#r;'S[;'S;=`#R<%lO[~zWOY[Zr[s#O[#P#q[#q#r!d#r;'S[;'S;=`#R<%lO[~!iWQ~OY[Zr[s#O[#P#q[#q#r!d#r;'S[;'S;=`#R<%lO[~#UP;=`<%l[",
  tokenizers: [0],
  topRules: { Program: [0, 1] },
  tokenPrec: 0,
});
